very raw draft
HerringtonDarkholme/typescript-repl pull request #19
Opened 2016-12-05 09:52 UTC by RGBD

Fixes #18.
Here's a very raw but working prototype.
It would be awesome to add completion for file path.

2016-12-05 09:55 UTC, HerringtonDarkholme commented
Please use the internal TypeScript service to transpile the file at once, and send it vm in one command.

2016-12-05 09:58 UTC, HerringtonDarkholme requested changes

2016-12-05 09:58 UTC, HerringtonDarkholme commented on src/repl.ts
> +    let file_contents: string = fs.readFileSync(filename, 'utf8')
Use `path.resolve` to get the absolute path.

2016-12-05 09:58 UTC, HerringtonDarkholme commented on src/repl.ts
> +    let file_contents: string = fs.readFileSync(filename, 'utf8')
Please use camel-case.

2016-12-05 09:58 UTC, HerringtonDarkholme commented on src/repl.ts
> +    console.log(colorize(file_contents))
Don't log intermediate file content unless under verbose mode.

2016-12-05 09:58 UTC, HerringtonDarkholme commented on src/repl.ts
> +      loadFile(code.split(' ')[1])
Possible `undefined`

2016-12-05 09:58 UTC, HerringtonDarkholme commented on src/repl.ts
> +    console.log(`// loading file ${filename}`.cyan)
Should it support both js or ts?

2016-12-06 16:36 UTC, RGBD commented on src/repl.ts
> +    console.log(`// loading file ${filename}`.cyan)
I think it should. Also I think **:load** command should accept a list of files instead of just one.

2016-12-06 16:39 UTC, RGBD commented on src/repl.ts
> +    console.log(colorize(file_contents))
I thought verbose mode implied printing out transpiled **javascript**.
Also, printing out the entire file is whate node does on **.load**.

2016-12-06 16:44 UTC, HerringtonDarkholme commented on src/repl.ts
> +    console.log(colorize(file_contents))
this repl has been quite different from nodejs' repl. I don't know keeping same with node is good.

2016-12-12 19:10 UTC, RGBD commented
> Please use the internal TypeScript service to transpile the file at once, and send it vm in one command.
I'm not sure what's the point of this.
Loaded code still has to be checked for errors. Code typed by user after load command **needs** to know what code was loaded to correctly check for errors. I mean, to keep program working as expected we need to do most part of **startEvaluate** function's job. Also it would be strange if :print command wouldn't include sources of loaded files.

2016-12-13 02:06 UTC, HerringtonDarkholme commented
My point back then is that loaded file should not be fed to service line by line, but as one code block as a whole. Since the implementation has been changed I think it is fine.

2016-12-13 02:21 UTC, HerringtonDarkholme requested changes

2016-12-13 02:21 UTC, HerringtonDarkholme commented on src/repl.ts
> +    let fileContents: string = fs.readFileSync(filePath, 'utf8')
Please remove the annotation since fs.readFileSync's return type is clearly string

2016-12-13 02:21 UTC, HerringtonDarkholme commented on src/service.ts
> -  var codes = getDeclarationFiles().map(dir => `/// <reference path="${dir}" />`)
why change this line?

2016-12-13 02:21 UTC, HerringtonDarkholme commented on src/repl.ts
> +      let files = (code.match(/\S+/g) || []).slice(1);
what if there is a space in the filename? I think `load` command can load only one file at one time

2016-12-13 02:23 UTC, HerringtonDarkholme commented
The implementation overall is good to me. Still some detail might need changes.

2016-12-13 08:01 UTC, RGBD commented on src/service.ts
> -  var codes = getDeclarationFiles().map(dir => `/// <reference path="${dir}" />`)
Not having a newline at the end here leads to errors if appended text doesn't start with a newline. Try checking out old version of this file and **:load** any .ts file that doesn't start with a newline as a first command to repl.

I know i can just prepend file contents with a newline, but what I did is more robust.

2016-12-13 08:05 UTC, RGBD commented on src/repl.ts
> +      let files = (code.match(/\S+/g) || []).slice(1);
I can change it to allow spaces inside quotes.
```
:load foo.ts "bar baz.ts"
```

2016-12-13 08:07 UTC, HerringtonDarkholme commented on src/repl.ts
> +      let files = (code.match(/\S+/g) || []).slice(1);
Why permitting multiple load? I wonder why you need to load file at all. repl is a small playground. If you need load multiple files, `tsc --init` and fire up an editor is clearly better.

2016-12-13 08:26 UTC, RGBD commented on src/repl.ts
> +      let files = (code.match(/\S+/g) || []).slice(1);
Okay, fine.

2016-12-16 05:13 UTC, HerringtonDarkholme approved these changes

2016-12-16 05:14 UTC, merged